version: '3.7'

services:
  nbthsbusapp:
    build: .
    ports:
      - "8000:5000"
    env_file: .env
    restart: always
    depends_on:
      - mysql


  mysql:
    image: "mysql/mysql-server:5.7"
    env_file: .env_mysql
    restart: always
