services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  nbthsbusapp:
    build: .
    container_name: nbthsbusapp_v2
    restart: always
    env_file:
      - ./config/.env
    environment:
      APP_NAME: MyApp
    ports:
      - "8080:8080"
    expose:
      - "8080"

  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local