version: '3.7'

services:
  nbthsbusapp:
    build: .
    command: sh -c "sleep 10 ; python app.py"
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
    ports:
      - "3360:3306"
