services:
  nginx:
    build: ../nginx
    container_name: nginx
    restart: always
    depends_on:
      - nbthsbusapp
    ports:
      - "80:80"

  nbthsbusapp:
    build: ..
    container_name: nbthsbusapp_v2
    restart: always
    env_file:
      - ../config/.env
    environment:
      APP_NAME: MyApp
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql-container
    restart: always
    env_file:
      - ../config/.env
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ${APP_DATABASE}
      MYSQL_USER: ${APP_USER}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local